
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MastersTime
{

    public int Id { get; set; }

    public int MasterId { get; set; }

    public System.DateTime DateTime { get; set; }

    public string Status { get; set; }



    public virtual Users Users { get; set; }

}

}
