
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Orders
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public int PaymentMethodId { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public System.DateTime DeliveryDate { get; set; }



    public virtual PaymentMethods PaymentMethods { get; set; }

    public virtual Products Products { get; set; }

    public virtual Users Users { get; set; }

}

}
