
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyProject.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Products
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Products()
    {

        this.Cart = new HashSet<Cart>();

        this.Orders = new HashSet<Orders>();

    }


    public int Id { get; set; }

    public int ManufacturerId { get; set; }

    public int ProductTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public Nullable<decimal> Sale { get; set; }

    public byte[] IsFreezed { get; set; }

    public decimal Rate { get; set; }

    public string ImagePath { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cart> Cart { get; set; }

    public virtual Manufacturers Manufacturers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orders> Orders { get; set; }

    public virtual ProductTypes ProductTypes { get; set; }

}

}
