//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdPlace { get; set; }
        public decimal Price { get; set; }
        public int IdSession { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
